name: "Trial"
on:
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            apk_file=$(find "${{ github.workspace }}" -type f -name 'temp.apk' -print -quit)
            if [ -z "$apk_file" ]; then
              echo "No APK file found"
              echo 'github.workspace === ${{ github.workspace }}'

              exit 1
            fi
            echo "APK file found: $apk_file"
            echo "${{ github.workspace }}" 
            echo "$apk_file"
          retention-days: 3
